<a href="https://colab.research.google.com/github/arpit-parejiya01/ML_Algorithm/blob/main/ML_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df= pd.read_csv("CR_data.csv")


In [ ]:
df.drop(['match_event_id','game_season','area_of_shot','shot_basics','range_of_shot','team_name','date_of_game','home/away','shot_id_number','lat/lng','type_of_shot','type_of_combined_shot','match_id','team_id'],axis=1,inplace=True)

In [ ]:
df.head(2)

Unnamed: 0  location_x  location_y  remaining_min  power_of_shot  \
0           0       167.0        72.0           10.0            1.0   
1           1      -157.0         0.0           10.0            1.0   

   knockout_match  remaining_sec  distance_of_shot  is_goal  remaining_min.1  \
0             0.0           27.0              38.0      NaN             10.0   
1             0.0           22.0              35.0      0.0             10.0   

   power_of_shot.1  knockout_match.1  remaining_sec.1  distance_of_shot.1  
0              1.0            50.608             54.2                38.0  
1              1.0            28.800             22.0                35.0

In [ ]:
df['remaining_min.1'].mode()

0    0.0
Name: remaining_min.1, dtype: float64

In [ ]:
df['location_x'].fillna(value = 0,inplace=True)

In [ ]:
df['location_y'].fillna(value = 0,inplace=True)

In [ ]:
df['remaining_min'].fillna(value = 0,inplace=True)

In [ ]:
df['power_of_shot'].fillna(value = 3,inplace=True)

In [ ]:
df['knockout_match'].fillna(value = 0,inplace=True)

In [ ]:
df['remaining_sec'].fillna(value = 0,inplace=True)

In [ ]:
df['distance_of_shot'].fillna(value = 20,inplace=True)

In [ ]:
df['is_goal'].fillna(value = 0,inplace=True)

In [ ]:
df['power_of_shot.1'].fillna(value = 3,inplace=True)

In [ ]:
df['knockout_match.1'].fillna(value = 0,inplace=True)

In [ ]:
df['remaining_sec.1'].fillna(value = 0,inplace=True)

In [ ]:
df['distance_of_shot.1'].fillna(value = 20,inplace=True)

In [ ]:
df['remaining_min.1'].fillna(value = 0,inplace=True)

In [ ]:
df.isnull().sum()

Unnamed: 0            0
location_x            0
location_y            0
remaining_min         0
power_of_shot         0
knockout_match        0
remaining_sec         0
distance_of_shot      0
is_goal               0
remaining_min.1       0
power_of_shot.1       0
knockout_match.1      0
remaining_sec.1       0
distance_of_shot.1    0
dtype: int64

# **# LogisticRegression Accuracy Score**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
x = df[["location_x","location_y","remaining_min","power_of_shot","remaining_sec","remaining_min.1","power_of_shot.1","remaining_sec.1"]]
y = df[['is_goal']]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model = LogisticRegression()
model.fit(x_train,y_train)
prediction = model.predict(x_test)
accu=accuracy_score(y_test,prediction)
print(prediction)
print(accu)

[0. 0. 0. ... 0. 0. 0.]
0.6366449511400651


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## **DicisionTree Accuracy Score**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
x = df[["location_x","location_y","remaining_min","power_of_shot","remaining_sec","remaining_min.1","power_of_shot.1","remaining_sec.1"]]
y = df[['is_goal']]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model = DecisionTreeClassifier()
model.fit(x_train,y_train)
prediction = model.predict(x_test)
accu=accuracy_score(y_test,prediction)
print(prediction)
print(accu)

[1. 1. 0. ... 1. 0. 1.]
0.5555374592833876


## **RendomForest Accuracy Score**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
x = df[["location_x","location_y","remaining_min","power_of_shot","remaining_sec","remaining_min.1","power_of_shot.1","remaining_sec.1"]]
y = df[['is_goal']]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model = RandomForestClassifier()
model.fit(x_train,y_train)
prediction = model.predict(x_test)
accu=accuracy_score(y_test,prediction)
print(prediction)
print(accu)

<ipython-input-44-7aeaf35d9223>:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x_train,y_train)


[0. 0. 0. ... 0. 0. 1.]
0.6231270358306189


### **KNN**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
x = df[["location_x","location_y","remaining_min","power_of_shot","remaining_sec","remaining_min.1","power_of_shot.1","remaining_sec.1"]]
y = df[['is_goal']]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
prediction = model.predict(x_test)
accu=accuracy_score(y_test,prediction)
print(prediction)
print(accu)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


[1. 0. 0. ... 1. 0. 0.]
0.5684039087947883


### **K-Means**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
x = df[["location_x","location_y","remaining_min","power_of_shot","remaining_sec","remaining_min.1","power_of_shot.1","remaining_sec.1"]]
y = df[['is_goal']]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model = KMeans(n_clusters=2, random_state=0, n_init="auto").fit(x)
model.fit(x_train,y_train)
prediction = model.predict(x_test)
accu=accuracy_score(y_test,prediction)
print(prediction)
print(accu)

[0 1 1 ... 1 1 1]
0.498371335504886
